### ISSUE TITLE
use of rand() for password generation..

### ISSUE THREAD

**Issue by jjarmoc** [trustedsec/SHIPS#1]
Rand() in Ruby uses a Mersenne Twister as documented at http://ruby-doc.org/core-2.1.1/Random.html
MT state can be recovered given a small number of samples.  

For something security sensitive, like generating random passwords and nonces, you probably want OpenSSL's secure_random, /dev/random, or /dev/urandom instead.

https://github.com/trustedsec/SHIPS/blob/master/lib/computer.rb#L130
https://github.com/trustedsec/SHIPS/blob/master/lib/computer.rb#L82

**Comment by trustedsec** [comment]
Valid points there - switched over to securerandom which is already built into ruby:

2a3
> require 'securerandom'
82c83
<     v = (1 + rand(2147483646)).to_s if v.nil?
---
>     v = (1 + SecureRandom.random_number(2147483646)).to_s if v.nil?
90c91
<   
---
>   
130c131
<       newpwd = Array.new(@@password_length) { rand(94) + 30 } #array of printing chars
---
>       newpwd = Array.new(@@password_length) { SecureRandom.random_number(94) + 30 } #array of printing chars

Appreciate the post and considering this one closed (fixes already pushed). Thanks again!
