### ISSUE TITLE
Monitoring attack?

### ISSUE THREAD

**Issue by JDogHerman** [trustedsec/SHIPS#3]
Also it seems (and I could be wrong here) that you send the nonce in the URL. Would this not allow a monitoring attack as the Cert is not verified before sending the request? (Client sends get request "https://172.16.235.1/password?name=$HOST&nonce=$NONCE" but is not able to connect. {for whatever reason} That client will try again later but that request was sniffed from threat agent and then replayed as the URL request would not be encrypted with the servers HTTPS Cert)

I apologize if I am missing something in the process.

**Comment by trustedsec** [comment]
The nonce is to remove the ability to brute force initial requests upon request time - if they were able to intercept the initial request and go to the URL again by spoofing the initial request they could possibly (rarely) be requested again if you were to spoof the initial request. With the nonce there it removes that ability. The certs are handled via the client scripts and is imperative when they are there that a valid certificate is checked for. Both the Linux and Windows scripts currently have this - so it would eliminate the ability to intercept those. The client scripts are a framework - you could conceivably add additional configurations in the client scripts to only trust root certificates of the company. Right now they do validate and only accept passing the password to a server that has a legitimate certificate (and hostname) that is in the system.

**Comment by GeoffWalton** [comment]
You are not missing anything.  The nonce value only weakly authenticates the client.  Its a trade off to keep the request model as light weight and simple as possible.  It would be possible arrange to intercept a client requests, discover and discover its nonce secret.

With that you could make new request to SHIPS server.  It will provide the attacker a new password.  This will also have the side effect of preventing the legitimate client from updating its password, If server is being monitored these failures will show up in request logs.   The attacker learns nothing about the password in use currently on the legitimate client.  That is still secure.  Worst case situation (that we are aware of) is the attacker issues multiple requests and overwrites all the previous password slots for the client, leaving the administrators with no correct password for that client.

The client should be retrying.  Once the client is moved to a safe network,  the administrator can clear the nonce value on the server, which will cause it to accept the next client request, at which time the client will set that password for itself.  So the situation may be recovered that way.

**Comment by JDogHerman** [comment]
Makes sense, I wonder how I could detect that an alternative machine is impersonating some of my clients and making them rouge devices.
