### ISSUE TITLE
Install link on www.trustedsec.com 404

### ISSUE THREAD

**Issue by bandrel** [trustedsec/SHIPS#5]
Link provided on www.trustedsec.com/ships/ points to https://github.com/trustedsec/SHIPS/raw/master/doc/SHIPS_Installation_v1.pdf which is a dead link.

**Comment by JDogHerman** [comment]
The link should be updated to:
https://github.com/trustedsec/SHIPS/raw/master/doc/SHIPS_Installation_v2.pdf

**Comment by trustedsec** [comment]
Fixed, thanks!
